### ISSUE TITLE
gcc for 7.2

### ISSUE THREAD

**Issue by Zohman** [habemus-papadum/gcc-holy-build#1]
Hi,

 thanks for sharing!

can you be kind and create one for 7.2.0?

i'm looking for gcc 7.2.0 to work on SLES10..
your gcc 6.3.0 is working for me.. iv'e tried to build 7.2 many time without success.. :(
thought maybe you have some cross distro portable like this..

i don't care about docker, i tried to clone and edit your files to much 7.2,
but i see the sources are'nt from official GNU..

your advice is much appreciated here, thanks!

**Comment by habemus-papadum** [comment]
Hi  - i had a quick look.  tldr, i'm not sure when I'll have time to do this.  

Here are some notes for myself/others for when I get a chance:

A first glance, the following should have worked:
````
git clone, cd, mkdir build
cmake .. -DLIL_TAG=gcc-7_2_0-release  
````
However, the build fails due to the needed versions of GMP, MFPR, etc are missing.  This a fairly easy fix, but should be done correctly. 

For my gcc6.3 I created a custom branch that bundled these dependencies (I believe that's the only change I made wrt upstream)

Better to allow a cmake flag that  runs the dependency download script bundled with modern gcc's

Also for each major version of gcc, someone should verify that the logic in`gcc-postfix.sh` is correct (refer to whatever is being done in conda)

**Comment by Zohman** [comment]
Hi,
thanks for the answer!

i tried to follow the steps until this "custom branch" where i didn't know how to proceed..
hope that you will have some time to compile it or give some key notes that one can follow.

very much appreciated!

**Comment by habemus-papadum** [comment]
Let me know if https://github.com/habemus-papadum/gcc-holy-build/releases/tag/v7.2.0-r1 works for you.

**Comment by Zohman** [comment]
had some issues with binutils, but after compiling a suitable binutils into your gcc root folder
and prefixing the PATH, everything worked.

Thanks a lot!

**Comment by habemus-papadum** [comment]
that's good news!  Out of curiosity, do you have extra details/logs re: the binutils issue/work around?  Unless you have anything else, I'll close this in a a few days.
